import './components/q-chat-item/index.js'
import './components/q-chat-list/index.js'
import './components/q-main-tab/index.js'
import './components/q-chat-header/index.js'
import './components/q-friend-item/index.js'
import './components/q-friend-list/index.js'
